//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesseract.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tesseract.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert image to 8 bpp..
        /// </summary>
        public static string ColorQuantizer_ConvertTo8Bpp_Failed_to_convert_image_to_8_bpp_ {
            get {
                return ResourceManager.GetString("ColorQuantizer_ConvertTo8Bpp_Failed_to_convert_image_to_8_bpp_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All weights must be greater than or equal to zero; {0} was not..
        /// </summary>
        public static string GrayscaleConverter_ConvertRgbToGray_All_weights_must_be_greater_than_or_equal_to_zero___0__was_not_ {
            get {
                return ResourceManager.GetString("GrayscaleConverter_ConvertRgbToGray_All_weights_must_be_greater_than_or_equal_to_" +
                        "zero___0__was_not_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert to grayscale..
        /// </summary>
        public static string GrayscaleConverter_ConvertRgbToGray_Failed_to_convert_to_grayscale_ {
            get {
                return ResourceManager.GetString("GrayscaleConverter_ConvertRgbToGray_Failed_to_convert_to_grayscale_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to binarize image..
        /// </summary>
        public static string ImageBinarizer_BinarizeOtsuAdaptiveThreshold_Failed_to_binarize_image_ {
            get {
                return ResourceManager.GetString("ImageBinarizer_BinarizeOtsuAdaptiveThreshold_Failed_to_binarize_image_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} parameter must be greater than or equal to {1}..
        /// </summary>
        public static string ImageBinarizer_BinarizeOtsuAdaptiveThreshold_The__0__parameter_must_be_greater_than_or_equal_to__1__ {
            get {
                return ResourceManager.GetString("ImageBinarizer_BinarizeOtsuAdaptiveThreshold_The__0__parameter_must_be_greater_th" +
                        "an_or_equal_to__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor must be greater than zero (0)..
        /// </summary>
        public static string ImageBinarizer_BinarizeSauvola_Factor_must_be_greater_than_zero__0__ {
            get {
                return ResourceManager.GetString("ImageBinarizer_BinarizeSauvola_Factor_must_be_greater_than_zero__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to invert image..
        /// </summary>
        public static string ImageInverter_InvertImage_Failed_to_invert_image_ {
            get {
                return ResourceManager.GetString("ImageInverter_InvertImage_Failed_to_invert_image_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rotate image around its centre..
        /// </summary>
        public static string ImageRotator_RotateImage_Failed_to_rotate_image_around_its_centre_ {
            get {
                return ResourceManager.GetString("ImageRotator_RotateImage_Failed_to_rotate_image_around_its_centre_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rotate image..
        /// </summary>
        public static string ImageRotator_RotateImage90_Failed_to_rotate_image_ {
            get {
                return ResourceManager.GetString("ImageRotator_RotateImage90_Failed_to_rotate_image_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid direction value..
        /// </summary>
        public static string ImageRotator_RotateImage90_Invalid_direction_value_ {
            get {
                return ResourceManager.GetString("ImageRotator_RotateImage90_Invalid_direction_value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove lines from image..
        /// </summary>
        public static string LineRemover_RemoveHorizontalLines_Failed_to_remove_lines_from_image_ {
            get {
                return ResourceManager.GetString("LineRemover_RemoveHorizontalLines_Failed_to_remove_lines_from_image_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to despeckle image..
        /// </summary>
        public static string NoiseRemover_ReduceSpeckleNoise_Failed_to_despeckle_image_ {
            get {
                return ResourceManager.GetString("NoiseRemover_ReduceSpeckleNoise_Failed_to_despeckle_image_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to detect image orientation..
        /// </summary>
        public static string Page_DetectBestOrientationAndScript_Failed_to_detect_image_orientation_ {
            get {
                return ResourceManager.GetString("Page_DetectBestOrientationAndScript_Failed_to_detect_image_orientation_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get thresholded image..
        /// </summary>
        public static string Page_GetThresholdedImage_Failed_to_get_thresholded_image_ {
            get {
                return ResourceManager.GetString("Page_GetThresholdedImage_Failed_to_get_thresholded_image_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The region of interest to be processed must be within the image bounds..
        /// </summary>
        public static string Page_RegionOfInterest_The_region_of_interest_to_be_processed_must_be_within_the_image_bounds_ {
            get {
                return ResourceManager.GetString("Page_RegionOfInterest_The_region_of_interest_to_be_processed_must_be_within_the_i" +
                        "mage_bounds_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to compare pix.
        /// </summary>
        public static string Pix_Equals_Failed_to_compare_pix {
            get {
                return ResourceManager.GetString("Pix_Equals_Failed_to_compare_pix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth must be 1, 2, 4, or 8 bpp..
        /// </summary>
        public static string PixColorMapFactory_CreateLinear_Depth_must_be_1__2__4__or_8_bpp_ {
            get {
                return ResourceManager.GetString("PixColorMapFactory_CreateLinear_Depth_must_be_1__2__4__or_8_bpp_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth must be 1, 2, 4, 8, 16, or 32 bits..
        /// </summary>
        public static string PixFactory_Create_Depth_must_be_1__2__4__8__16__or_32_bits_ {
            get {
                return ResourceManager.GetString("PixFactory_Create_Depth_must_be_1__2__4__8__16__or_32_bits_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height must be greater than zero.
        /// </summary>
        public static string PixFactory_Create_Height_must_be_greater_than_zero {
            get {
                return ResourceManager.GetString("PixFactory_Create_Height_must_be_greater_than_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pix handle must not be zero (null)..
        /// </summary>
        public static string PixFactory_Create_Pix_handle_must_not_be_zero__null__ {
            get {
                return ResourceManager.GetString("PixFactory_Create_Pix_handle_must_not_be_zero__null__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width must be greater than zero.
        /// </summary>
        public static string PixFactory_Create_Width_must_be_greater_than_zero {
            get {
                return ResourceManager.GetString("PixFactory_Create_Width_must_be_greater_than_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deskew image..
        /// </summary>
        public static string SkewCorrector_DeskewImage_Failed_to_deskew_image_ {
            get {
                return ResourceManager.GetString("SkewCorrector_DeskewImage_Failed_to_deskew_image_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bitmap&apos;s pixel format of {0} was not recognised..
        /// </summary>
        public static string TesseractDrawingExtensions_GetBpp_The_bitmap_s_pixel_format_of__0__was_not_recognised_ {
            get {
                return ResourceManager.GetString("TesseractDrawingExtensions_GetBpp_The_bitmap_s_pixel_format_of__0__was_not_recogn" +
                        "ised_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize the Tesseract engine..
        /// </summary>
        public static string TesseractEngine_Initialize_Failed_to_initialize_the_Tesseract_engine_ {
            get {
                return ResourceManager.GetString("TesseractEngine_Initialize_Failed_to_initialize_the_Tesseract_engine_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image region to be processed must be within the image bounds..
        /// </summary>
        public static string TesseractEngine_Process_The_image_region_to_be_processed_must_be_within_the_image_bounds_ {
            get {
                return ResourceManager.GetString("TesseractEngine_Process_The_image_region_to_be_processed_must_be_within_the_image" +
                        "_bounds_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index value must be between zero (0) and {0}..
        /// </summary>
        public static string The_index_value_must_be_between_zero_and__0__ {
            get {
                return ResourceManager.GetString("The_index_value_must_be_between_zero_and__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or whitespace..
        /// </summary>
        public static string Value_cannot_be_null_or_whitespace {
            get {
                return ResourceManager.GetString("Value_cannot_be_null_or_whitespace", resourceCulture);
            }
        }
    }
}
